services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/html
    environment:
      - APP_ENV=development
      - PHP_IDE_CONFIG=serverName=todo-api
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - backend

  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - backend

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend
    ports:
      - "33066:3306"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"

networks:
  backend:

volumes:
  db_data:
